apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata-pvc
  labels:
    application: paf
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
