apiVersion: v1
kind: Pod
metadata:
  name: greetings
  labels:
    app: greetings
spec:
  containers:
    - name: greet
      image: mindthump/greet
      imagePullPolicy: IfNotPresent
    - name: fruit
      image: mindthump/fruit_server
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
