apiVersion: v1
kind: Pod
metadata:
  name: greet
spec:
  containers:
    - name: greet
      image: mindthump/greet:francie
      command: ["sleep"]
      args: ["1d"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Never
