version: '3.7'

services:
  greet:
    image: mindthump/greet

    # Keep the container running (for a day) doing nothing = lets us shell in
    # We don't need this if it's actually running a service (e.g., http)
    # Also, this overrides "CMD" in the Dockerfile.
    command: sleep 1d
    # command: python greet.py --greeting "Yo"

    environment:
      - NAME=Harvey

    # I don't do anything with this (yet).
    volumes:
      - type: volume
        source: sample-vol
        target: /appdata

  spew:
    image: kennethreitz/httpbin

    deploy:
      replicas: 3

    ports:
      - "8081:80"

  watch:
    image: dockersamples/visualizer

    ports:
      - "8080:8080"

    deploy:
      placement:
        constraints: [node.role == manager]

    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  sample-vol:
