version: '3.8'

volumes:
  appdata:

networks:
  app-net:

secrets:
  user-info:
    # Yup, plain text in the VCS.
    file: ./secrets.txt

services:
  greet:
    build:
      context: .
      target: greet_server
    image: mindthump/greet:${REVISION}
    container_name: greet
    # Keep the container running (for a day) doing nothing = lets us shell in
    # We don't need this if it's actually running a service (e.g., http)
    # Also, this overrides "ENTRYPOINT" in the Dockerfile.
    entrypoint: sleep
    command: 1d
    environment:
      - NAME=Harvey
      - AFW_LOG_DIR=/data
    volumes:
      - type: volume
        source: appdata
        target: /data
    networks:
      - app-net
    secrets:
      - user-info

  fruit:
    # Dumb json list of fruit
    build:
      context: .
      target: fruit_server
    image: mindthump/fruit_server:${REVISION}
    container_name: fruit
    ports:
      - "8088:80"
    networks:
      - app-net
    command: gunicorn --reload -b 0.0.0.0:80 fruit_server:app -k gevent
    environment:
      - AFW_LOG_DIR=/data
    volumes:
      - type: volume
        source: appdata
        target: /data

  spew:
    image: kennethreitz/httpbin
    container_name: spew
    ports:
      - "8081:80"
    networks:
      - app-net

  stash:
    # Use 'http://localhost:5984/_utils/' for UI
    image: couchdb
    container_name: stash
    ports:
      - "5984:5984"
    networks:
      - app-net
    volumes:
      - type: volume
        source: appdata
        target: /data
