version: '3.7'

volumes:
  appdata:

networks:
  app-net:
    driver: overlay
    attachable: true

secrets:
  user-info:
    # Yup, plain text in the VCS.
    file: ./secrets.txt

services:
  greet:
    image: mindthump/greet
    init: true
    # Keep the container running (for a day) doing nothing = lets us shell in
    # We don't need this if it's actually running a service (e.g., http)
    # Also, this overrides "ENTRYPOINT" in the Dockerfile.
    entrypoint: sleep
    command: 1d

    environment:
      - NAME=Harvey
      - AFW_LOG_DIR=/data

    volumes:
      - ./greet_app:/app/greet_app
      - type: volume
        source: appdata
        target: /data

    networks:
      - app-net

    secrets:
      - user-info

  spew:
    image: kennethreitz/httpbin

    deploy:
      replicas: 3

    ports:
      - "8081:80"

    networks:
      - app-net

  watch:
    image: dockersamples/visualizer

    ports:
      - "8080:8080"

    deploy:
      placement:
        constraints: [node.role == manager]

    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

    networks:
      - app-net

  stash:
    # Use 'http://localhost:5984/_utils/' for UI
    # TODO: This needs persistent storage
    image: couchdb

    ports:
      - "5984:5984"

    networks:
      - app-net

  fruit:
    # Dumb json list of fruit
    image: mindthump/fruit_server:camille

    ports:
      - "8088:8000"

    networks:
      - app-net

    command: gunicorn --reload -b 0.0.0.0:8000 fruit_server_app.fruit_server:app -k gevent

    environment:
      - AFW_LOG_DIR=/data

    volumes:
      - ./fruit_server_app:/app/fruit_server_app
      - type: volume
        source: appdata
        target: /data
