apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-deployment
  labels:
    project: paf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit
  template:
    metadata:
      labels:
        app: fruit
        project: paf
    spec:
      hostname: fruit-pod
      containers:
        - name: fruit
          command:
            - gunicorn
          args:
            - --reload
            - -b
            - 0.0.0.0:8088
            - fruit_server_app.fruit_server:app
            - -k
            - gevent
          image: mindthump/fruit-server:20230906-2029
          env:
            - name: AFW_LOG_DIR
              value: /data
          tty: true
          ports:
            - containerPort: 8088
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: appdata
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata-pvc
