apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fruit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fruit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/app-net: "true"
        io.kompose.service: fruit
    spec:
      containers:
        - name: fruit
          args:
            - gunicorn
            - --reload
            - -b
            - 0.0.0.0:80
            - fruit_server:app
            - -k
            - gevent
          env:
            - name: AFW_LOG_DIR
              value: /data
          image: 'mindthump/fruit-server'
          tty: true
          ports:
            - containerPort: 80
          resources: {}
          # This must be here for minikube to get internal images
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: appdata
      restartPolicy: Always
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata
status: {}
