apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-deployment
  labels:
    app: fruit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit
  template:
    metadata:
      labels:
        app: fruit
    spec:
      containers:
        - name: fruit
          args:
            - gunicorn
            - --reload
            - -b
            - 0.0.0.0:80
            - fruit_server_app.fruit_server:app
            - -k
            - gevent
          image: 'mindthump/fruit-server'
          env:
            - name: AFW_LOG_DIR
              value: /data
          tty: true
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: appdata
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata
