---
apiVersion: v1
kind: Service
metadata:
  name: fruit
  labels:
    application: paf
spec:
  type: ClusterIP
  selector:
    app: fruit
  ports:
    - name: fruit
      port: 80
      targetPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: fruit-nodeport
spec:
  type: NodePort
  ports:
    - name: fruit
      port: 80
      targetPort: 8088
      nodePort: 30088
  selector:
    app: fruit
