apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: greet-job
  labels:
    application: paf
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: paf
        spec:
          containers:
            - name: greet
              command:
                - python
              args:
                - greet.py
              image: docker.io/mindthump/greet:20230907-1303
              env:
                - name: IN_CONTAINER
                  value: 'OK'
                - name: AFW_LOG_DIR
                  value: '/data'
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - name: user-secret-volume
                mountPath: /opt/secret-data
              - name: appdata
                mountPath: /data
              - name: users-volume
                mountPath: /opt/user-data
          restartPolicy: Never
          volumes:
            - name: appdata
              persistentVolumeClaim:
                claimName: appdata-pvc
            - name: user-secret-volume
              secret:
                secretName: user-info-secret
            - name: users-volume
              configMap:
                name: users
