apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet
  template:
    metadata:
      labels:
        app: greet
    spec:
      containers:
        - args:
            - 1d
          command:
            - sleep
          env:
            - name: AFW_LOG_DIR
              value: /data
            - name: NAME
              value: Harvey
          image: 'mindthump/greet'
          name: greet
          resources: {}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /run/secrets/user-info
              name: user-info
            - mountPath: /data
              name: appdata
      restartPolicy: Always
      volumes:
        - name: user-info
          secret:
            items:
              - key: user-info
                path: user-info
            secretName: user-info
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata
