apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: greet-job
  labels:
    application: paf
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: paf
        spec:
          containers:
            - name: greet-job
              command:
                - python
              args:
                - greet.py
              image: mindthump/greet-app:r20230822a2
              env:
                - name: IN_CONTAINER
                  value: 'OK'
                - name: AFW_LOG_DIR
                  value: '/data'
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - name: user-secret-volume
                mountPath: /etc/secret-volume
              - name: appdata
                mountPath: /data
          restartPolicy: Never
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          volumes:
            - name: appdata
              persistentVolumeClaim:
                claimName: appdata
            - name: user-secret-volume
              secret:
                secretName: user-info-secret
