apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-deployment
  labels:
    application: paf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet
  template:
    metadata:
      labels:
        application: paf
    spec:
      containers:
        - name: greet-container
          command:
            - sleep
          args:
            - 1d
          image: docker.io/mindthump/greet:20230901-0720
          env:
            - name: IN_CONTAINER
              value: 'OK'
            - name: AFW_LOG_DIR
              value: '/data'
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: user-secret-volume
            mountPath: /etc/secret-volume
          - name: appdata
            mountPath: /data
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata-pvc
        - name: user-secret-volume
          secret:
            secretName: user-info-secret
