apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-deployment
  labels:
    app: greet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet
  template:
    metadata:
      labels:
        app: greet
    spec:
      containers:
        - name: greet-container
          command:
            - sleep
          args:
            - 1d
          image: mindthump/greet
          env:
            - name: IN_CONTAINER
              value: TRUE
            - name: AFW_LOG_DIR
              value: /data
          imagePullPolicy: Never
          volumeMounts:
          - name: user-info
            mountPath: /run/secrets/user-info
          - name: appdata
            mountPath: /data
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata
        - name: user-info
          secret:
            secretName: user-info
            items:
              - key: user-info
                path: user-info
