apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-deployment
  labels:
    project: paf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet
  template:
    metadata:
      labels:
        app: greet
        project: paf
    spec:
      containers:
        - name: greet
          command:
            - sleep
          args:
            - 1d
          image: docker.io/mindthump/greet:20230907-1303
          env:
            - name: IN_CONTAINER
              value: 'OK'
            - name: AFW_LOG_DIR
              value: '/data'
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: user-secret-volume
            mountPath: /opt/secret-data
          - name: appdata
            mountPath: /data
          - name: users-volume
            mountPath: /opt/user-data
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata-pvc
        - name: user-secret-volume
          secret:
            secretName: user-info-secret
        - name: users-volume
          configMap:
            name: users
