apiVersion: v1
kind: Pod
metadata:
  name: greet-pod
  labels:
    app: greet
spec:
  volumes:
    - name: appdata
      persistentVolumeClaim:
        claimName: appdata
    - name: user-info
      secret:
        secretName: user-info
        items:
          - key: user-info
            path: user-info
  containers:
    - name: greet-container
      image: mindthump/greet
      imagePullPolicy: Never
      command:
        - sleep
      args:
        - 1d
      env:
        - name: USERNAME
          value: Harvey
        - name: AFW_LOG_DIR
          value: /data
      volumeMounts:
        - name: user-info
          mountPath: /run/secrets/user-info
        - name: appdata
          mountPath: /data
