kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oebs-device-pvc
  labels:
    application: paf
spec:
  storageClassName: openebs-device
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
