kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oebs-hostpath-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5M
