apiVersion: apps/v1
kind: Deployment
metadata:
  name: spew
  labels:
    application: paf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spew-pod
  template:
    metadata:
      labels:
        application: paf
    spec:
      containers:
        - image: kennethreitz/httpbin
          name: spew-container
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
