apiVersion: apps/v1
kind: Deployment
metadata:
  name: spew-deployment
  labels:
    app: spew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spew-pod
  template:
    metadata:
      labels:
        app: spew-pod
    spec:
      containers:
        - image: kennethreitz/httpbin
          name: spew-container
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
